### PR TITLE
Minors changes for JOSS paper

### PR DESCRIPTION
**Pull request by JanJereczek**
This PR includes following minor changes:
- My second affiliation has been removed
- `/paper` has been excluded from codecov, which should largely address #64
- The abstracts have been removed from `paper.bib`
- The url link for the documentation in `paper.md` has been fixed

### CODE REVIEW

**Comment by Datseris** [comment]
it is a waste of computational resources to constantly build the PDF of the paper in every single PR. Let's please remove the draft-pdf workflow once you have managed to build the paper once.

**Comment by JanJereczek** [comment]
Documentation is not built properly because of a change in the interplay between `trajectory` and `obtain_state` in DynamicalSystemsBase.jl (used in logisitc example of the docs).

**Comment by Datseris** [comment]
Fixed in https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/pull/201

@JanJereczek , some advice for the future. If you have found an error, paste it. Don't just say "this error happened", copy the error message and paste it. Or alternatively copy the CI log line that has the error if you don't want to paste the entire thing. Let's not duplicate the effort to find the bug, which in some cases like now is trivial, but in general is non zero.

**Comment by JanJereczek** [comment]
Thanks for fixing it @Datseris. The PR should be ready to merge! You are right, I will include the error messages in future :)

**Review by Datseris — APPROVED** [review]

**Pull request merged**
